### ISSUE TITLE
sproto嵌入ulua

### ISSUE THREAD

**Issue by yksalun** [jarjin/SimpleFramework_UGUI#3]
你好，我这边本地下载的最新的ulua源代码，嵌入了最新的sproto，修改了sh文件后make成功，但是ulua.dll在用的时候提示找不到sproto.core，然后我用SimpleFramework_UGUI的ulua.dll放到本地工程里使用是可以的，请问sproto嵌入后的ulua源工程可以共享么？或者指点下可能哪里出了问题？
谢谢。

**Comment by jarjin** [comment]
https://github.com/jarjin/ulua_runtime_project/tree/master/win_build_src
